---
# Add a file to the vouch-proxy config directory
- name: Add Vouch-Proxy Config 
  template:
    src: "templates/VouchProxy/vouch_config.yml.j2"
    dest: "{{ base_install_dir }}/vouch/config.yml"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  become: yes