---
# Create the base directories needed by prometheus
- name: Create Vouch-Proxy Directories
  block:
      
    - name: "Create Vouch-Proxy directories"
      file:
        path: "{{ base_install_dir }}/vouch"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
     
    - name: "Create Vouch-Proxy Data directories"
      file:
        path: "{{ base_data_dir }}/vouch/data"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
  become: yes